### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by infinitytec** [chexbox/Algebra-Calculator#2]
We should work out a couple of sketches.

**Comment by chexbox** [comment]
Good Idea. You can upload any you have drawn in a folder. (Pull request?)

**Comment by infinitytec** [comment]
![image](https://user-images.githubusercontent.com/13670462/38399724-a9d2cfca-3911-11e8-9c5a-fd320be8824d.png)
Just a quick mock up, similar to what you have done.

**Comment by chexbox** [comment]
Here's my TI30XIIS:
![img_20180406_131420](https://user-images.githubusercontent.com/31783961/38437323-b150f6d8-399c-11e8-8244-15318b6e3905.jpg)

**Comment by infinitytec** [comment]
What do you think of the changes?

**Comment by infinitytec** [comment]
We should come up with a standardized design for the s-b-s milestone.

**Comment by infinitytec** [comment]
All buttons that I add will now be just 'dummy buttons.' They will become active once #23 is ready.

Another idea is to render s-b-s in another box. The result/current formula can be in the current text box, and then steps can be shown elsewhere(once again, requires #23 ).

**Comment by infinitytec** [comment]
Whoa, this new green theme is awesome!
@chexbox what do you think?

**Comment by chexbox** [comment]
Sorry for not seeing all these comments. They look great!

**Comment by chexbox** [comment]
It looks like this has been inactive and off-topic. Make an "Announcement" issue for now on; Closing
