### ISSUE TITLE
Choosing a Colour Scheme

### ISSUE THREAD

**Issue by chexbox** [chexbox/Algebra-Calculator#22]
I'm not sure I like our use of colour as it is too close to scratch's colours. Discuss below possible replacements. (Green?)

**Comment by infinitytec** [comment]
I just picked it because I needed something and I  couldn't find a good green. :P

**Comment by chexbox** [comment]
No, I did. it didn't look any good.

**Comment by infinitytec** [comment]
Let's use #2 to discuss.
