### ISSUE TITLE
Look into using Bootstrap

### ISSUE THREAD

**Issue by infinitytec** [chexbox/Algebra-Calculator#29]
As mentioned in #11

**Comment by Wetbikeboy2500** [comment]
You might want to look into [MaterializeCss](http://materializecss.com/about.html) since it has the same theme you are going for on the site.

**Comment by infinitytec** [comment]
That is an idea, but what we have seems to be working right now. We could use that in a future version.

**Comment by infinitytec** [comment]
Closing, as we will probably just go with what we have.
