### ISSUE TITLE
Calculate page

### ISSUE THREAD

**Issue by chexbox** [chexbox/Algebra-Calculator#40]
Here is a quick mock-up for a new page.
![2018-04-11-164810_1279x655_scrot](https://user-images.githubusercontent.com/31783961/38645048-4f441780-3da8-11e8-9360-f87202b5e9d6.png)

**Comment by infinitytec** [comment]
Maybe put the special keys on the left? I think it would be more consistent with what users would expect.

**Comment by chexbox** [comment]
> Maybe put the special keys on the left? I think it would be more consistent with what users would expect.
Yes, This was made fast, so I didn't think about that.
