### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by infinitytec** [chexbox/Algebra-Calculator#44]
Just some ideas:

- jsCalc

- WebCalc

- OpenCalc (there is an old calculator with this name)

- Calc.js

- OpenAlgebra

**Comment by chexbox** [comment]
Just some more ideas.
* AlgCalc
* OpenAlgCalc
* AlgCalcWeb
* jsAlgebra

**Comment by infinitytec** [comment]
OpenWebCalc
Calcul8 (idk about this one)
LibreWebCalc

**Comment by chexbox** [comment]
Any support for the name AlgCalc?
Advantages:
* Currently there isn't other calculators with this name. (as far as I know)
* It is shorter than spelling out Algebra Calculator every time.
Any thoughts about this?
